### ISSUE TITLE
Display portfolio of past projects

### ISSUE THREAD

**Issue by WSMorrison** [WSMorrison/Portfolio#5]
Visitor will be able to see past portfolio projects when visiting the site

This feature is not complete until:
- [ ] There is a place for a list of school projects
- [ ] There is a place for a list of personal projects
- [ ] There is a place for a list of professional projects
